In [12]:
import json
import pandas as pd
import pymongo
import matplotlib as mpl
import numpy as np
import matplotlib.pyplot as plt

myclient = pymongo.MongoClient("mongodb://localhost:27017/")
mydb = myclient["soccerData"]
mycol = mydb["midRawData"]
data = pd.DataFrame(list(mycol.find()))

data_new = data.drop_duplicates()
data_new['masterMidGoal'] = data_new['masterMidGoal'].astype(np.int64)
data_new['guestMidGoal'] = data_new['guestMidGoal'].astype(np.int64)
data_new = data_new.drop(['_id', 'time','place'], axis=1)

In [13]:
data_new.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 73388 entries, 0 to 73387
Data columns (total 28 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   masterGoal               73388 non-null  int64
 1   guestGoal                73388 non-null  int64
 2   masterMidGoal            73388 non-null  int64
 3   guestMidGoal             73388 non-null  int64
 4   yapanMasterStartOdd      73388 non-null  float64
 5   yapanGuestStartOdd       73388 non-null  float64
 6   yapanPankouStart         73388 non-null  object
 7   yapanMasterOdd           73388 non-null  float64
 8   yapanGuestOdd            73388 non-null  float64
 9   yapanPankou              73388 non-null  object
 10  yapanMasterStartOddMid   73388 non-null  float64
 11  yapanGuestStartOddMid    73388 non-null  float64
 12  yapanPankouStartMid      73388 non-null  object
 13  yapanMasterOddMid        73388 non-null  float64
 14  yapanGuestOddMid         73388 non-null  float64
 15  yapanPankouMid           73388 non-null  object
 16  daxiaoMasterStartOdd     73388 non-null  float64
 17  daxiaoGuestStartOdd      73388 non-null  float64
 18  daxiaoPankouStart        73388 non-null  object
 19  daxiaoMasterOdd          73388 non-null  float64
 20  daxiaoGuestOdd           73388 non-null  float64
 21  daxiaoPankou             73388 non-null  object
 22  daxiaoMasterStartOddMid  73388 non-null  float64
 23  daxiaoGuestStartOddMid   73388 non-null  float64
 24  daxiaoPankouStartMid     73388 non-null  object
 25  daxiaoMasterOddMid       73388 non-null  float64
 26  daxiaoGuestOddMid        73388 non-null  float64
 27  daxiaoPankouMid          73388 non-null  object
dtypes: float64(16), int64(4), object(8)
memory usage: 16.2+ MB

In [14]:

def df2mongo(df, mycol):
    records = json.loads(df.T.to_json()).values()
    mycol.remove()
    result = mycol.insert_many(records)
    return result

def get18(master,guest):
    if master > guest:
        return 18
    if master < guest:
        return 81
    if master == guest:
        return 99
    
def getType(yapanMasterStartOdd, yapanGuestStartOdd, yapanPankouStart):
    linTypeStart = get18(yapanMasterStartOdd, yapanGuestStartOdd)
    return str(linTypeStart) + yapanPankouStart

def getUpDownGoal(masterGoal, guestGoal, masterMidGoal,guestMidGoal):
    masterGoalMid = masterGoal - masterMidGoal
    guestGoalMid = guestGoal - guestMidGoal
    return masterGoalMid - guestGoalMid

def getGoalMid(masterGoal, guestGoal, masterMidGoal,guestMidGoal):
    if masterGoal + guestGoal - masterMidGoal - guestMidGoal >= 4:
        return 4
    else:
        return masterGoal + guestGoal - masterMidGoal - guestMidGoal

def getResultMid(masterGoal, guestGoal, masterMidGoal,guestMidGoal):
    masterGoalMid = masterGoal - masterMidGoal
    guestGoalMid = guestGoal - guestMidGoal
    if masterGoalMid > guestGoalMid:
        return 3
    if masterGoalMid == guestGoalMid:
        return 1
    if masterGoalMid < guestGoalMid:
        return 0
    
def getResult(masterGoal, guestGoal):
    if masterGoal > guestGoal:
        return 3
    if masterGoal == guestGoal:
        return 1
    if masterGoal < guestGoal:
        return 0
    
def removeSub(pankou):
    pankou = pankou.replace("升","")
    pankou = pankou.replace("降","")
    return pankou.strip()


def getbili(fenzi, master, peace, guest):
    return (fenzi / (master + peace + guest)) * 100

def getbiliV2(fenzi,x):
    return (fenzi / (x['0'] + x['1']+ x['2']+ x['3']+ x['4'])) * 100
            
def getbiliV3(fenzi,x):
    if x == 0:
        return 0
    return (fenzi / x) * 100

In [15]:
data_new['daxiaoPankouStart'] = data_new.apply(lambda x: removeSub(x['daxiaoPankouStart']), axis=1)
data_new['daxiaoPankou'] = data_new.apply(lambda x: removeSub(x['daxiaoPankou']), axis=1)
data_new['daxiaoPankouStartMid'] = data_new.apply(lambda x: removeSub(x['daxiaoPankouStartMid']), axis=1)
data_new['daxiaoPankouMid'] = data_new.apply(lambda x: removeSub(x['daxiaoPankouMid']), axis=1)
data_new['goalMid'] = data_new.apply(lambda x: getGoalMid(
        x['masterGoal'], x['guestGoal'], x['masterMidGoal'], x['guestMidGoal']), axis=1)

data_new['daxiaoTypeStart'] = data_new.apply(lambda x: getType(
        x['daxiaoMasterStartOdd'], x['daxiaoGuestStartOdd'], x['daxiaoPankouStart']), axis=1)
data_new['daxiaoType'] = data_new.apply(lambda x: getType(
        x['daxiaoMasterOdd'], x['daxiaoGuestOdd'], x['daxiaoPankou']), axis=1)
data_new['daxiaoTypeStartMid'] = data_new.apply(lambda x: getType(
        x['daxiaoMasterStartOddMid'], x['daxiaoGuestStartOddMid'], x['daxiaoPankouStartMid']), axis=1)
data_new['daxiaoTypeMid'] = data_new.apply(lambda x: getType(
        x['daxiaoMasterOddMid'], x['daxiaoGuestOddMid'], x['daxiaoPankouMid']), axis=1)

data_new['result'] = data_new.apply(lambda x: getResult(
        x['masterGoal'], x['guestGoal']), axis=1)
data_new['resultMid'] = data_new.apply(lambda x: getResultMid(
        x['masterGoal'], x['guestGoal'], x['masterMidGoal'], x['guestMidGoal']), axis=1)


data_new['goalMid'] = data_new.apply(lambda x: getGoalMid(
        x['masterGoal'], x['guestGoal'], x['masterMidGoal'], x['guestMidGoal']), axis=1)

In [16]:
data_new[['daxiaoType','daxiaoTypeStartMid'
                    , "daxiaoTypeMid", "masterMidGoal", "guestMidGoal", "goalMid", "guestGoal"]]

,daxiaoType,daxiaoTypeStartMid,daxiaoTypeMid,masterMidGoal,guestMidGoal,goalMid,guestGoal
0,182/2.5,181/1.5,181/1.5,0,0,1,1
1,183.5,184,184,2,0,4,0
2,183.5/4,813.5/4,184,1,1,3,3
3,182.5,181/1.5,181/1.5,0,0,0,0
4,183/3.5,812.5/3,812.5/3,1,0,4,3
...,...,...,...,...,...,...,...
73383,811.5/2,811,811,0,0,2,1
73384,993,812.5,812.5,0,1,0,1
73385,992.5/3,184.5,184.5,0,3,2,4
73386,183.5,812.5/3,812.5/3,0,1,2,2
73387,182/2.5,811,811,0,1,2,1

In [17]:
def staticDaxiao(data_new):
    data_new = data_new[data_new['goalMid'] >= 0]

    res = data_new[['daxiaoType','daxiaoTypeStartMid'
                    , "daxiaoTypeMid", "masterMidGoal", "guestMidGoal", "goalMid", "guestGoal"]]

    res = pd.pivot_table(data_new, index=['daxiaoType','daxiaoTypeStartMid','daxiaoTypeMid'
                                          , "masterMidGoal", "guestMidGoal"], columns=["goalMid"], aggfunc="count")

    res = res["guestGoal"]

    res = res.reset_index()

    a1 = res.fillna(0.0)

    a1.columns = ['daxiaoType','daxiaoTypeStartMid'
                    , "daxiaoTypeMid","masterMidGoal","guestMidGoal" ,'0', '1', '2','3', '4']


    a1['4Per'] = a1.apply(lambda x: getbiliV2(
        x["4"],x), axis=1)
    a1['3Per'] = a1.apply(lambda x: getbiliV2(
        x["3"],x), axis=1)
    a1['2Per'] = a1.apply(lambda x: getbiliV2(
        x["2"],x), axis=1)
    a1['1Per'] = a1.apply(lambda x: getbiliV2(
        x["1"], x), axis=1)
    a1['0Per'] = a1.apply(lambda x: getbiliV2(
        x["0"], x), axis=1)

    a1['da2Per'] = a1['4Per'] + a1['3Per'] + a1['2Per']
    
    a1['xi2Per'] = a1['1Per'] + a1['0Per']
    
    
    a1['k1Per'] = a1['4Per'] + a1['3Per'] + a1['2Per'] + a1['1Per']
    
    a1['k2Per'] = a1.apply(lambda x: getbiliV3(
        (x["2"] + x['3'] + x['4']), (x['1'] + x["2"] + x['3'] + x['4'])), axis=1)
    
    a1['k3Per'] = a1.apply(lambda x: getbiliV3(
       (x['3'] + x['4']), (x["2"] + x['3'] + x['4'])), axis=1)
    
    a1['k4Per'] = a1.apply(lambda x: getbiliV3(
       (x['4']), (x['3'] + x['4'])), axis=1)
    
    a1 = a1[(a1['0'] + a1['1'] + a1['2'] + a1['3'] + a1['4']) > 10]
    
    
#     a75 = a1[(a1['4Per'] > 65) | (a1['3Per'] > 65) | (a1['2Per'] > 65) | (
#         a1['2Per'] > 65) | (a1['da2Per'] > 65) | (a1['xi2Per'] > 65)]
    
    return  a1.drop(columns=['3Per', '2Per', '4Per', '1Per', '3Per', '0Per', '3Per', '3Per'])

In [18]:
a75 = staticDaxiao(data_new)
a75.sort_values(by = 'da2Per',ascending=False).head(20)

,daxiaoType,daxiaoTypeStartMid,daxiaoTypeMid,masterMidGoal,guestMidGoal,0,1,2,3,4,da2Per,xi2Per,k1Per,k2Per,k3Per,k4Per
7269,813/3.5,814,814,2,0,0.0,2.0,11.0,4.0,2.0,89.473684,10.526316,100.000000,89.473684,35.294118,33.333333
2122,183.5,184,184,2,0,2.0,3.0,15.0,9.0,8.0,86.486486,13.513514,94.594595,91.428571,53.125000,47.058824
2763,183/3.5,182,182,0,0,1.0,1.0,5.0,5.0,2.0,85.714286,14.285714,92.857143,92.307692,58.333333,28.571429
3236,184,183/3.5,183/3.5,1,0,1.0,1.0,5.0,3.0,2.0,83.333333,16.666667,91.666667,90.909091,50.000000,40.000000
2825,183/3.5,183.5/4,813.5,1,1,1.0,1.0,6.0,1.0,3.0,83.333333,16.666667,91.666667,90.909091,40.000000,75.000000
6772,813.5/4,813,183,1,0,0.0,2.0,6.0,2.0,2.0,83.333333,16.666667,100.000000,83.333333,40.000000,50.000000
2840,183/3.5,184,184,2,0,1.0,3.0,8.0,6.0,5.0,82.608696,17.391304,95.652174,86.363636,57.894737,45.454545
6598,813.5/4,183/3.5,183/3.5,0,1,1.0,2.0,6.0,6.0,2.0,82.352941,17.647059,94.117647,87.500000,57.142857,25.000000
7435,814,182/2.5,182/2.5,0,0,0.0,3.0,4.0,7.0,3.0,82.352941,17.647059,100.000000,82.352941,71.428571,30.000000
2120,183.5,184,184,0,2,1.0,1.0,4.0,4.0,1.0,81.818182,18.181818,90.909091,90.000000,55.555556,20.000000
6666,813.5/4,185/5.5,185/5.5,1,2,0.0,2.0,4.0,1.0,4.0,81.818182,18.181818,100.000000,81.818182,55.555556,80.000000
7577,814,813,813,1,0,0.0,2.0,3.0,2.0,4.0,81.818182,18.181818,100.000000,81.818182,66.666667,66.666667
7553,814,811.5/2,811.5/2,0,0,1.0,1.0,4.0,5.0,0.0,81.818182,18.181818,90.909091,90.000000,55.555556,0.000000
3235,184,183/3.5,183/3.5,0,1,2.0,0.0,5.0,2.0,2.0,81.818182,18.181818,81.818182,100.000000,44.444444,50.000000
6638,813.5/4,185,185,1,2,1.0,1.0,5.0,3.0,1.0,81.818182,18.181818,90.909091,90.000000,44.444444,25.000000
6665,813.5/4,185/5.5,185/5.5,0,3,2.0,0.0,3.0,3.0,3.0,81.818182,18.181818,81.818182,100.000000,66.666667,50.000000
811,182.5/3,182.5,812.5,1,0,0.0,4.0,8.0,6.0,3.0,80.952381,19.047619,100.000000,80.952381,52.941176,33.333333
8686,992/2.5,812/2.5,812/2.5,1,0,2.0,1.0,7.0,3.0,1.0,78.571429,21.428571,85.714286,91.666667,36.363636,25.000000
7225,813/3.5,813,813,1,0,2.0,2.0,5.0,6.0,3.0,77.777778,22.222222,88.888889,87.500000,64.285714,33.333333
5975,813,813.5/4,813.5/4,2,0,3.0,9.0,20.0,18.0,3.0,77.358491,22.641509,94.339623,82.000000,51.219512,14.285714

In [19]:
ss = a75[(a75['da2Per']>70) | (a75['xi2Per']>70)]
ss['sum'] = ss['3'] + ss['1'] + ss['0']
ss['sum'].sum()

<ipython-input-19-df8052458a7b>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ss['sum'] = ss['3'] + ss['1'] + ss['0']

3075.0

In [20]:
a75[a75['daxiaoType'] == '812.5/3'].sort_values(by = 'da2Per',ascending=False).head(20)

,daxiaoType,daxiaoTypeStartMid,daxiaoTypeMid,masterMidGoal,guestMidGoal,0,1,2,3,4,da2Per,xi2Per,k1Per,k2Per,k3Per,k4Per
4864,812.5/3,183.5/4,813.5,0,2,3.0,0.0,6.0,1.0,1.0,72.727273,27.272727,72.727273,100.000000,25.000000,50.000000
4776,812.5/3,181.5,811.5,0,0,3.0,6.0,8.0,9.0,3.0,68.965517,31.034483,89.655172,76.923077,60.000000,25.000000
4866,812.5/3,183.5/4,813.5,2,0,4.0,1.0,3.0,7.0,1.0,68.750000,31.250000,75.000000,91.666667,72.727273,12.500000
5146,812.5/3,814.5,814.5,3,0,4.0,6.0,13.0,7.0,2.0,68.750000,31.250000,87.500000,78.571429,40.909091,22.222222
5113,812.5/3,813.5/4,813.5/4,2,0,2.0,9.0,16.0,6.0,2.0,68.571429,31.428571,94.285714,72.727273,33.333333,25.000000
5143,812.5/3,814.5,814.5,1,2,8.0,9.0,19.0,5.0,10.0,66.666667,33.333333,84.313725,79.069767,44.117647,66.666667
5008,812.5/3,811.5,991.5,0,0,4.0,2.0,7.0,2.0,3.0,66.666667,33.333333,77.777778,85.714286,41.666667,60.000000
4862,812.5/3,183.5/4,183.5/4,2,0,5.0,13.0,13.0,12.0,8.0,64.705882,35.294118,90.196078,71.739130,60.606061,40.000000
5056,812.5/3,812.5/3,812.5/3,0,1,9.0,10.0,19.0,8.0,7.0,64.150943,35.849057,83.018868,77.272727,44.117647,46.666667
5257,812.5/3,992.5,182.5,0,1,1.0,3.0,5.0,0.0,2.0,63.636364,36.363636,90.909091,70.000000,28.571429,100.000000
4865,812.5/3,183.5/4,813.5,1,1,1.0,3.0,3.0,3.0,1.0,63.636364,36.363636,90.909091,70.000000,57.142857,25.000000
5142,812.5/3,814.5,814.5,0,3,4.0,6.0,8.0,7.0,2.0,62.962963,37.037037,85.185185,73.913043,52.941176,22.222222
4818,812.5/3,182.5/3,182.5/3,0,1,10.0,32.0,44.0,17.0,10.0,62.831858,37.168142,91.150442,68.932039,38.028169,37.037037
5012,812.5/3,811.5/2,811.5/2,0,0,0.0,6.0,7.0,2.0,1.0,62.500000,37.500000,100.000000,62.500000,30.000000,33.333333
4861,812.5/3,183.5/4,183.5/4,1,1,5.0,12.0,10.0,11.0,7.0,62.222222,37.777778,88.888889,70.000000,64.285714,38.888889
4819,812.5/3,182.5/3,182.5/3,1,0,9.0,18.0,30.0,9.0,5.0,61.971831,38.028169,87.323944,70.967742,31.818182,35.714286
5033,812.5/3,812.5,182.5/3,0,1,2.0,6.0,6.0,4.0,3.0,61.904762,38.095238,90.476190,68.421053,53.846154,42.857143
5034,812.5/3,812.5,182.5/3,1,0,4.0,4.0,5.0,5.0,2.0,60.000000,40.000000,80.000000,75.000000,58.333333,28.571429
4912,812.5/3,184.5/5,184.5/5,2,1,1.0,9.0,6.0,5.0,4.0,60.000000,40.000000,96.000000,62.500000,60.000000,44.444444
5088,812.5/3,813.5,183.5,1,1,2.0,4.0,4.0,5.0,0.0,60.000000,40.000000,86.666667,69.230769,55.555556,0.000000

In [21]:
a75[(a75['daxiaoType'] == '182.5') & (a75['daxiaoTypeStartMid'] == '181/1.5')]

,daxiaoType,daxiaoTypeStartMid,daxiaoTypeMid,masterMidGoal,guestMidGoal,0,1,2,3,4,da2Per,xi2Per,k1Per,k2Per,k3Per,k4Per
357,182.5,181/1.5,181/1.5,0,0,195.0,267.0,188.0,95.0,26.0,40.077821,59.922179,74.708171,53.645833,39.158576,21.487603
361,182.5,181/1.5,811,0,0,11.0,28.0,14.0,12.0,0.0,40.000000,60.000000,83.076923,48.148148,46.153846,0.000000
363,182.5,181/1.5,811/1.5,0,0,6.0,14.0,8.0,3.0,3.0,41.176471,58.823529,82.352941,50.000000,42.857143,50.000000

In [22]:
mydb = myclient["soccerData"]
mycol = mydb["staticMidDaxiao"]
df2mongo(a75, mycol)

<ipython-input-14-a1e8c402b0e2>:3: DeprecationWarning: remove is deprecated. Use delete_one or delete_many instead.
  mycol.remove()